import streamlit as st
import plotly.express as px
import pandas as pd
import sys
import os

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from app.modules.enrichment import enrich_company
from app.modules.icp_scoring import score_lead
from app.modules.email_gen import generate_email
from app.modules.chat_assistant import ask_pipeline
from app.modules.gmail_sender import send_email

st.set_page_config(page_title="RevenueOS", page_icon="🚀", layout="wide")

st.title("🚀 RevenueOS")
st.caption("AI-powered lead enrichment, scoring, and outreach automation")

@st.cache_data
def load_data():
    path = os.path.join(os.path.dirname(__file__), '..', 'data', 'leads_dataset.csv')
if os.path.exists(path):
        return pd.read_csv(path)
    return pd.DataFrame()

df = load_data()

with st.sidebar:
st.header("➕ Add New Lead")
    first_name = st.text_input("First Name", "Sarah")
    last_name = st.text_input("Last Name", "Johnson")
    email = st.text_input("Email", "sarah@example.com")
    company = st.text_input("Company", "TechCorp")
    job_title = st.text_input("Job Title", "CEO")
    source = st.selectbox("Source", ["referral", "linkedin", "website", "cold_email", "webinar", "conference", "inbound"])
    analyze = st.button("🔍 Analyze Lead", use_container_width=True)

if analyze:
with st.spinner("Running AI analysis..."):
        lead_data = {"first_name": first_name, "last_name": last_name, "email": email, "company": company, "job_title": job_title, "source": source}
        company_data = enrich_company(company)
        scoring = score_lead(lead_data, company_data)
        grade = scoring["grade"]
        score = scoring["score"]
        email_content = generate_email(lead_data, company_data, scoring) if grade == "HOT" else None
        st.session_state["analysis"] = {"lead_data": lead_data, "company_data": company_data, "scoring": scoring, "grade": grade, "score": score, "email_content": email_content}

tab1, tab2, tab3 = st.tabs(["📊 Pipeline Dashboard", "🤖 AI Assistant", "📋 All Leads"])

with tab1:
if "analysis" in st.session_state:
        r = st.session_state["analysis"]
        st.subheader(f"Lead Analysis: {r['lead_data']['first_name']} {r['lead_data']['last_name']}")
        col1, col2, col3, col4, col5 = st.columns(5)
        col1.metric("ICP Score", f"{r['score']}/100")
        col2.metric("Grade", f"{'🔥' if r['grade']=='HOT' else '🌡️' if r['grade']=='WARM' else '❄️'} {r['grade']}")
        col3.metric("Industry", r["company_data"].get("industry", "Unknown"))
        col4.metric("Employees", r["company_data"].get("employees", 0))
        col5.metric("Revenue", r["company_data"].get("revenue", "Unknown"))
        st.divider()
        c1, c2 = st.columns(2)
        with c1:
            st.subheader("👤 Lead & Company Info")
            st.write(f"**Name:** {r['lead_data']['first_name']} {r['lead_data']['last_name']}")
            st.write(f"**Title:** {r['lead_data']['job_title']}")
            st.write(f"**Company:** {r['lead_data']['company']}")
            st.write(f"**Industry:** {r['company_data'].get('industry', 'Unknown')}")
            st.write(f"**Location:** {r['company_data'].get('location', 'Unknown')}")
            st.write(f"**Revenue:** {r['company_data'].get('revenue', 'Unknown')}")
        with c2:
            st.subheader("✉️ AI Generated Email")
            if r["grade"] == "HOT" and r["email_content"]:
                st.text_area("Generated Email", value=r["email_content"], height=200)
                st.success("✅ Email generated by Claude AI")
                col_a, col_b = st.columns(2)
                col_a.download_button("📥 Download", r["email_content"], file_name=f"email_{r['lead_data']['first_name']}.txt")
                if col_b.button("📧 Send via Gmail"):
                    success, msg = send_email(r["lead_data"]["email"], f"Quick note for {r['lead_data']['first_name']}", r["email_content"])
                    if success:
                        st.success(f"✅ Email sent to {r['lead_data']['email']}")
                    else:
                        st.error(f"❌ Failed: {msg}")
            else:
                st.info(f"Score is {r['score']}/100 — AI email triggers at 40+")
        st.divider()

if not df.empty:
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Total Leads", len(df))
        col2.metric("🔥 Hot", len(df[df["status"]=="hot"]))
        col3.metric("🌡️ Warm", len(df[df["status"]=="warm"]))
        col4.metric("❄️ Cold", len(df[df["status"]=="cold"]))
        c1, c2 = st.columns(2)
        with c1:
            fig1 = px.histogram(df, x="icp_score", color="status", title="ICP Score Distribution", color_discrete_map={"hot":"#ff4b4b","warm":"#ffa500","cold":"#4b9dff"})
            fig1.update_layout(paper_bgcolor="rgba(0,0,0,0)", font={"color":"white"})
            st.plotly_chart(fig1, use_container_width=True)
        with c2:
            fig2 = px.bar(df["industry"].value_counts().reset_index(), x="industry", y="count", title="Leads by Industry", color_discrete_sequence=["#7c83fd"])
            fig2.update_layout(paper_bgcolor="rgba(0,0,0,0)", font={"color":"white"})
            st.plotly_chart(fig2, use_container_width=True)
        c3, c4 = st.columns(2)
        with c3:
            fig3 = px.pie(df, names="source", title="Lead Sources", color_discrete_sequence=["#ff4b4b","#ffa500","#7c83fd","#4b9dff","#00cc96"])
            fig3.update_layout(paper_bgcolor="rgba(0,0,0,0)", font={"color":"white"})
            st.plotly_chart(fig3, use_container_width=True)
        with c4:
            trend = df.groupby("date_added").size().reset_index(name="leads")
            fig4 = px.line(trend, x="date_added", y="leads", title="Leads Over Time", color_discrete_sequence=["#7c83fd"])
            fig4.update_layout(paper_bgcolor="rgba(0,0,0,0)", font={"color":"white"})
            st.plotly_chart(fig4, use_container_width=True)

with tab2:
st.subheader("🤖 Ask Anything About Your Pipeline")
st.caption("Powered by Claude AI")
if df.empty:
        st.warning("No dataset loaded.")
    else:
        if "chat_history" not in st.session_state:
            st.session_state.chat_history = []
        for msg in st.session_state.chat_history:
            with st.chat_message(msg["role"]):
                st.write(msg["content"])
        st.write("**Try asking:**")
        cols = st.columns(3)
        suggestions = ["Which industry has the most hot leads?", "Who should I contact first this week?", "What is my average ICP score?", "Which lead source converts best?", "How many leads came from LinkedIn?", "Show me top 5 leads to prioritize"]
        for i, s in enumerate(suggestions):
            if cols[i % 3].button(s, key=f"sug_{i}"):
                st.session_state.chat_history.append({"role": "user", "content": s})
                with st.spinner("Thinking..."):
                    answer = ask_pipeline(s, df)
                st.session_state.chat_history.append({"role": "assistant", "content": answer})
                st.rerun()
        question = st.chat_input("Ask about your pipeline...")
        if question:
            st.session_state.chat_history.append({"role": "user", "content": question})
            with st.spinner("Thinking..."):
                answer = ask_pipeline(question, df)
            st.session_state.chat_history.append({"role": "assistant", "content": answer})
            st.rerun()
        if st.button("🗑️ Clear Chat"):
            st.session_state.chat_history = []
            st.rerun()

with tab3:
st.subheader("📋 Full Lead Database")
if df.empty:
        st.warning("No leads found.")
    else:
        col1, col2, col3 = st.columns(3)
        status_filter = col1.selectbox("Filter by Status", ["All", "hot", "warm", "cold"])
        industry_filter = col2.selectbox("Filter by Industry", ["All"] + sorted(df["industry"].unique().tolist()))
        source_filter = col3.selectbox("Filter by Source", ["All"] + sorted(df["source"].unique().tolist()))
        filtered = df.copy()
        if status_filter != "All":
            filtered = filtered[filtered["status"] == status_filter]
        if industry_filter != "All":
            filtered = filtered[filtered["industry"] == industry_filter]
        if source_filter != "All":
            filtered = filtered[filtered["source"] == source_filter]
        st.write(f"Showing **{len(filtered)}** leads")
        st.dataframe(filtered.sort_values("icp_score", ascending=False), use_container_width=True)
        csv = filtered.to_csv(index=False)
        st.download_button("📥 Export CSV", csv, file_name="filtered_leads.csv", mime="text/csv")
